### PR TITLE
Pi tft

### PR DESCRIPTION
**Pull request by TheVince81**
Hey,
The button functions do great, but the backlight one doesn't seem to work. How can this thing come ? Nothing happened to my PiTFT when I tried to use merely the function, even without joining it to the button effects. Someone to help me around, to switch off/on the backlight ?
Thank you

### CODE REVIEW

**Comment by elParaguayo** [comment]
Can you get the backlight to work if you follow the instructions on the Adafruit website?

**Comment by elParaguayo** [comment]
I've just tested the code again on my Pi and it does work exactly as it should. e.g. if I do:

<pre><code>import pitftgpio
pi = pitftgpio.PiTFT_GPIO()
pi.Backlight(False)</code></pre>

the light turns off. So I can't reproduce your issue unless you provide some more information.

**Comment by TheVince81** [comment]
Hello,

I'm sorry, I have no excuse, I don't know why, it works perfectly now.
I spent hours yesterday, but today, just 2 minutes were enough. Thank you and once again, sorry, this is some great piece of work !

**Comment by elParaguayo** [comment]
No problem. Delighted to hear that it works for you.

**Pull request closed without merging**
